import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "bootstrap/dist/js/bootstrap.js";
import "bootstrap/dist/css/bootstrap.css";
import "@/styles/index.css";
import CryptoDropdown from "./components/CryptoDropdown.vue";
import Spinner from "./components/Spinner.vue";
const app = createApp(App);
app.component("CryptoDropdown", CryptoDropdown);
app.component("Spinner", Spinner);
app.use(store);
app.use(router);
app.mount("#app");
